### ISSUE TITLE
[QUESTION] How do I download the icons for rofi?

### ISSUE THREAD

**Issue by iksvoklisav** [Manas140/dotfiles#12]
How can I change my icons to yours on the rofi launcher?

**Comment by Manas140** [comment]
if you see there is no icon theme provided in the config. So, it uses the defaults, all you have to do is install papirus icon theme and set it as default through lxappearance 
![image](https://user-images.githubusercontent.com/64472354/149940876-178cdf7a-ac3a-4474-ae99-b65cf5af862f.png)

**Comment by iksvoklisav** [comment]
Thanks
